/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinesys;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.PasswordAuthentication;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Transport;


/**
 *
 * @author Umayanga
 */
public class AdminSendMail extends javax.swing.JFrame {

    /**
     * Creates new form AdminSendMail
     */
    public AdminSendMail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topic = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        to = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        subject = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        totxt = new javax.swing.JTextField();
        fromtxt = new javax.swing.JTextField();
        subjecttxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgtxt = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Send mail");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topic.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        topic.setForeground(new java.awt.Color(255, 255, 255));
        topic.setText("Send Mail ");
        jPanel1.add(topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        create.setBackground(new java.awt.Color(255, 51, 51));
        create.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        create.setText("Send");
        create.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
        });
        jPanel1.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 460, 168, 50));

        to.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        to.setForeground(new java.awt.Color(255, 255, 255));
        to.setText("To ");
        jPanel1.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        from.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        from.setForeground(new java.awt.Color(255, 255, 255));
        from.setText("From");
        jPanel1.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        subject.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        subject.setForeground(new java.awt.Color(255, 255, 255));
        subject.setText("Subject");
        jPanel1.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        msg.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        msg.setForeground(new java.awt.Color(255, 255, 255));
        msg.setText("Message");
        jPanel1.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        totxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(totxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 530, 40));

        fromtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fromtxt.setText("rideemaliyaddamedical@gmail.com");
        jPanel1.add(fromtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 530, 40));

        subjecttxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(subjecttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 530, 40));

        msgtxt.setColumns(20);
        msgtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        msgtxt.setRows(5);
        jScrollPane1.setViewportView(msgtxt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 530, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img/mail.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img/back.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img/background.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
        String ToEmail = totxt.getText();
        String FromEmail = fromtxt.getText();
        String FromEmailPassword = "7553889Ur@";   //Your email password
        String Subjects = subjecttxt.getText();
        
        Properties properties = new Properties();
        properties.put("mail.smtp.auth","true");
        properties.put("mail.smtp.starttls.enable","true"); 
        properties.put("mail.smtp.host","smtp.gmail.com");
        properties.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory"); 
	properties.setProperty("mail.smtp.socketFactory.fallback", "false"); 
	properties.setProperty("mail.smtp.port", "465"); 
	properties.setProperty("mail.smtp.socketFactory.port", "465");
        
        Session session = Session.getDefaultInstance(properties,new javax.mail.Authenticator(){
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(FromEmail,FromEmailPassword);
            }
        });
        
        try{
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(FromEmail));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(ToEmail));
            message.setSubject(Subjects);
            message.setText(msgtxt.getText());
            Transport.send(message);
            
        }catch(Exception ex){
            System.out.println("Mail Sent Successfully"+ex);
        }
        
    }//GEN-LAST:event_createMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         AdminHomepage home = new AdminHomepage();

        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSendMail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton create;
    private javax.swing.JLabel from;
    private javax.swing.JTextField fromtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msg;
    private javax.swing.JTextArea msgtxt;
    private javax.swing.JLabel subject;
    private javax.swing.JTextField subjecttxt;
    private javax.swing.JLabel to;
    private javax.swing.JLabel topic;
    private javax.swing.JTextField totxt;
    // End of variables declaration//GEN-END:variables
}
