/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinesys;

/**
 *
 * @author Umayanga
 */
public class AdminInfectedDetails extends javax.swing.JFrame {

    /**
     * Creates new form AdminInfectedDetails
     */
    public AdminInfectedDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NIC = new javax.swing.JLabel();
        Fname = new javax.swing.JLabel();
        Lname6 = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        occupation = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        phone = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        addresstxt = new javax.swing.JTextField();
        NICtxt = new javax.swing.JTextField();
        Lnametxt = new javax.swing.JTextField();
        Fnametxt = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        NICDeltxt = new javax.swing.JTextField();
        NICDel = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Infected Details");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NIC.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 18)); // NOI18N
        NIC.setForeground(new java.awt.Color(255, 255, 255));
        NIC.setText("NIC number");
        jPanel1.add(NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 140, 30));

        Fname.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 18)); // NOI18N
        Fname.setForeground(new java.awt.Color(255, 255, 255));
        Fname.setText("First name");
        jPanel1.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        Lname6.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 18)); // NOI18N
        Lname6.setForeground(new java.awt.Color(255, 255, 255));
        Lname6.setText("Last name");
        jPanel1.add(Lname6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        address.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 18)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText("Address");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        occupation.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 18)); // NOI18N
        occupation.setForeground(new java.awt.Color(255, 255, 255));
        occupation.setText("Infected date");
        jPanel1.add(occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        back.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        back.setText("<<");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 30));

        phone.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 18)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setText("Phone number");
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));
        jPanel1.add(phonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 260, 30));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 260, 30));
        jPanel1.add(addresstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 260, 30));
        jPanel1.add(NICtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 260, 30));
        jPanel1.add(Lnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 260, 30));
        jPanel1.add(Fnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 260, 30));

        add.setBackground(new java.awt.Color(255, 51, 51));
        add.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        add.setText("Add");
        add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 130, 40));

        update1.setBackground(new java.awt.Color(255, 51, 51));
        update1.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        update1.setText("Update");
        update1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        update1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update1MouseClicked(evt);
            }
        });
        jPanel1.add(update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 130, 40));
        jPanel1.add(NICDeltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 190, 30));

        NICDel.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 18)); // NOI18N
        NICDel.setForeground(new java.awt.Color(255, 255, 255));
        NICDel.setText("NIC number");
        jPanel1.add(NICDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 140, 30));

        delete.setBackground(new java.awt.Color(255, 51, 51));
        delete.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        delete.setText("Delete");
        delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 130, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img/background.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1100, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        AdminHomepage home = new AdminHomepage();

        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseClicked

    private void update1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update1MouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        PHIViewCitizen citizen = new PHIViewCitizen();

        citizen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInfectedDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInfectedDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInfectedDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInfectedDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminInfectedDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fname;
    private javax.swing.JTextField Fnametxt;
    private javax.swing.JLabel Lname6;
    private javax.swing.JTextField Lnametxt;
    private javax.swing.JLabel NIC;
    private javax.swing.JLabel NICDel;
    private javax.swing.JTextField NICDeltxt;
    private javax.swing.JTextField NICtxt;
    private javax.swing.JButton add;
    private javax.swing.JLabel address;
    private javax.swing.JTextField addresstxt;
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JTextField date;
    private javax.swing.JButton delete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel occupation;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
