/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinesys;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.PasswordAuthentication;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Transport;
import javax.swing.JOptionPane;



/**
 *
 * @author Umayanga
 */
public class OfficerSendMail extends javax.swing.JFrame {

    /**
     * Creates new form OfficerSendMail
     */
    public OfficerSendMail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topic = new javax.swing.JLabel();
        send = new javax.swing.JButton();
        from = new javax.swing.JLabel();
        subject = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        to = new javax.swing.JLabel();
        subjecttxt = new javax.swing.JTextField();
        fromtxt = new javax.swing.JTextField();
        totxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgtxt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Send Mail");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topic.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        topic.setForeground(new java.awt.Color(255, 255, 255));
        topic.setText("Send Mail ");
        jPanel1.add(topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        send.setBackground(new java.awt.Color(255, 51, 51));
        send.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        send.setText("Send");
        send.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });
        jPanel1.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, 160, 50));

        from.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        from.setForeground(new java.awt.Color(255, 255, 255));
        from.setText("From");
        jPanel1.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        subject.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        subject.setForeground(new java.awt.Color(255, 255, 255));
        subject.setText("Subject");
        jPanel1.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        msg.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        msg.setForeground(new java.awt.Color(255, 255, 255));
        msg.setText("Message");
        jPanel1.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        to.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        to.setForeground(new java.awt.Color(255, 255, 255));
        to.setText("To ");
        jPanel1.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        subjecttxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(subjecttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 530, 40));

        fromtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fromtxt.setText("rideemaliyaddamedical@gmail.com");
        jPanel1.add(fromtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 530, 40));

        totxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(totxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 530, 40));

        msgtxt.setColumns(20);
        msgtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        msgtxt.setRows(5);
        jScrollPane1.setViewportView(msgtxt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 530, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img/back.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img/mail.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img/background.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked
        
        String ToEmail = totxt.getText();
        String FromEmail = fromtxt.getText();
        String FromEmailPassword = "7553889Ur@";   //Your email password
        String Subjects = subjecttxt.getText();
        
        Properties properties = new Properties();
        properties.put("mail.smtp.auth","true");
        properties.put("mail.smtp.starttls.enable","true"); 
        properties.put("mail.smtp.host","smtp.gmail.com");
        properties.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory"); 
	properties.setProperty("mail.smtp.socketFactory.fallback", "false"); 
	properties.setProperty("mail.smtp.port", "465"); 
	properties.setProperty("mail.smtp.socketFactory.port", "465");
        
        Session session = Session.getDefaultInstance(properties,new javax.mail.Authenticator(){
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(FromEmail,FromEmailPassword);
            }
        });
        
        try{
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(FromEmail));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(ToEmail));
            message.setSubject(Subjects);
            message.setText(msgtxt.getText());
            Transport.send(message);
            
        }catch(Exception ex){
            System.out.println("Mail Sent Successfully"+ex);
        }
        
       
        JOptionPane.showMessageDialog(null, "Email Sent Successfully");
                   totxt.setText("");
                   subjecttxt.setText("");
                   msgtxt.setText("");
                  
       
       
    }//GEN-LAST:event_sendMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        OfficerHomePage home = new OfficerHomePage();

        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfficerSendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfficerSendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfficerSendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfficerSendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OfficerSendMail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel from;
    private javax.swing.JTextField fromtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msg;
    private javax.swing.JTextArea msgtxt;
    private javax.swing.JButton send;
    private javax.swing.JLabel subject;
    private javax.swing.JTextField subjecttxt;
    private javax.swing.JLabel to;
    private javax.swing.JLabel topic;
    private javax.swing.JTextField totxt;
    // End of variables declaration//GEN-END:variables
}
