/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinesys;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Umayanga
 */
public class OfficerUserAccounts extends javax.swing.JFrame {

    DbConnection mdc = new DbConnection();
    
   
    public OfficerUserAccounts() {
        initComponents();
        AddUser();
    }

    
     void AddUser(){
    //      OfficerUserAcc account = new  OfficerUserAcc();
          
  
    Connection con=null;

       
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        phi = new javax.swing.JRadioButton();
        officer = new javax.swing.JRadioButton();
        admin = new javax.swing.JRadioButton();
        topic = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        pwd = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        pwdtxt = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UserAccounts");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(phi);
        phi.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        phi.setForeground(new java.awt.Color(255, 255, 255));
        phi.setText("PHI");
        jPanel1.add(phi, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, -1, -1));

        buttonGroup1.add(officer);
        officer.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        officer.setForeground(new java.awt.Color(255, 255, 255));
        officer.setText("Officer");
        jPanel1.add(officer, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        buttonGroup1.add(admin);
        admin.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("Admin");
        jPanel1.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        topic.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        topic.setForeground(new java.awt.Color(255, 255, 255));
        topic.setText("Create User Accounts");
        jPanel1.add(topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        name.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("User Name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 140, 30));

        pwd.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        pwd.setForeground(new java.awt.Color(255, 255, 255));
        pwd.setText("Password");
        jPanel1.add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        type.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setText("Type");
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        nametxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 400, 50));

        pwdtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(pwdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 400, 50));

        create.setBackground(new java.awt.Color(255, 51, 51));
        create.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        create.setText("Create");
        create.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
        });
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        jPanel1.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img/back.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img/acc.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        background.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img/background.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1100, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
        
     //   OfficerUserAcc user = new OfficerUserAcc();
        
      
        Connection con=null;
        
        try
        {
             con = DbConnection.getMyConnection();  //Add connection
           
            //String result=" INSERT INTO user (username, password, user_type) VALUES ('"+nametxt.getText()+"','"+pwdtxt.getText()+"', '"++"') ";
             
            String result=" INSERT INTO user (username, password, user_type) VALUES (?, ?, ?)";
            
            
            PreparedStatement ps=con.prepareStatement(result);
            
            
            ps.setString(1, nametxt.getText());
            ps.setString(2, pwdtxt.getText());
            
            String user_role = null;
            if(admin.isSelected()){
                user_role = admin.getText();
            }
            if(officer.isSelected()){
                user_role = officer.getText();
            }
            if(phi.isSelected()){
                user_role = phi.getText();
            }
            ps.setString(3, user_role);
            
            
            ps.executeUpdate();
           
            
        }
        
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
        
         JOptionPane.showMessageDialog(null, "Data Added successfully");
                   nametxt.setText("");
                   pwdtxt.setText("");
                   admin.setText("");
                   officer.setText("");
                   phi.setText("");
                  
    }//GEN-LAST:event_createMouseClicked

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        OfficerHomePage home = new OfficerHomePage();

        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfficerUserAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfficerUserAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfficerUserAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfficerUserAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OfficerUserAccounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nametxt;
    private javax.swing.JRadioButton officer;
    private javax.swing.JRadioButton phi;
    private javax.swing.JLabel pwd;
    private javax.swing.JTextField pwdtxt;
    private javax.swing.JLabel topic;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
