/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinesys;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Umayanga
 */
public class OfficerUserAccounts extends javax.swing.JFrame {

    DbConnection mdc = new DbConnection();
    
    
    
    public OfficerUserAccounts() {
        initComponents();
        AddUser();
    }

    
    
    
     void AddUser(){
          OfficerUserAcc account = new  OfficerUserAcc();
    
    Connection con=null;
     try
        {
                con = DbConnection.getMyConnection();   //Add connection
                
                String result = "SELECT * FROM medical";
                
                PreparedStatement ps = con.prepareStatement(result);
                ResultSet rs = ps.executeQuery();
     if(rs.next())
                {
                    nametxt.setText(rs.getString("username"));
                    pwdtxt.setText(rs.getString("password"));
                    admin.setText(rs.getString("user_type"));
                    officer.setText(rs.getString("user_type"));
                    phi.setText(rs.getString("user_type"));
                    
                }     
     
        }
        
   
        catch(Exception e)
        {
                javax.swing.JOptionPane.showMessageDialog(null,e);
        }
     
        nametxt.setText("");
        pwdtxt.setText("");
        admin.setText("");
        officer.setText("");
        phi.setText("");
       
    }
     
     
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        phi = new javax.swing.JRadioButton();
        topic = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        pwd = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        officer = new javax.swing.JRadioButton();
        admin = new javax.swing.JRadioButton();
        nametxt = new javax.swing.JTextField();
        pwdtxt = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        back = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UserAccounts");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phi.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        phi.setForeground(new java.awt.Color(255, 255, 255));
        phi.setText("PHI");
        jPanel1.add(phi, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, -1, -1));

        topic.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        topic.setForeground(new java.awt.Color(255, 255, 255));
        topic.setText("Create User Accounts");
        jPanel1.add(topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        name.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("User Name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 140, 30));

        pwd.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        pwd.setForeground(new java.awt.Color(255, 255, 255));
        pwd.setText("Password");
        jPanel1.add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        type.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setText("Type");
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        officer.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        officer.setForeground(new java.awt.Color(255, 255, 255));
        officer.setText("Officer");
        jPanel1.add(officer, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, -1, -1));

        admin.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 24)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("Admin");
        jPanel1.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));
        jPanel1.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 400, 50));
        jPanel1.add(pwdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 400, 50));

        create.setBackground(new java.awt.Color(255, 51, 51));
        create.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        create.setText("Create");
        create.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
        });
        jPanel1.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 160, 50));

        back.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        back.setText("<<");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 30));

        background.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img/background.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1100, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
        
        Connection myConn=null;
        
        try
        {
             myConn = DbConnection.getMyConnection();  //Add connection
           
            String result=" INSERT INTO user (username, password, user_type) VALUES ('"+getUsername()+"' ,'"+getpassword()+", '"+getUser_type()+"') ";
            
            
            PreparedStatement ps=myConn.prepareStatement(result);
            if(ps.execute()){
             
            }
            
        }
        
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
        
         JOptionPane.showMessageDialog(null, "Data Added successfully");
                   nametxt.setText("");
                   pwdtxt.setText("");
                   admin.setText("");
                   officer.setText("");
                   phi.setText("");
                  
    }//GEN-LAST:event_createMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        OfficerHomePage home = new OfficerHomePage();

        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfficerUserAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfficerUserAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfficerUserAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfficerUserAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OfficerUserAccounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin;
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JButton create;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nametxt;
    private javax.swing.JRadioButton officer;
    private javax.swing.JRadioButton phi;
    private javax.swing.JLabel pwd;
    private javax.swing.JTextField pwdtxt;
    private javax.swing.JLabel topic;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
