/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccinesys_PHI;

/**
 *
 * @author Umayanga
 */
public class PHIHomePage extends javax.swing.JFrame {

    /**
     * Creates new form PHIHomePage
     */
    public PHIHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ViewCitizen = new javax.swing.JButton();
        ViewVaccine = new javax.swing.JButton();
        ViewVaccinated = new javax.swing.JButton();
        ViewInfected = new javax.swing.JButton();
        topic = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PHI");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewCitizen.setBackground(new java.awt.Color(255, 51, 51));
        ViewCitizen.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        ViewCitizen.setForeground(new java.awt.Color(255, 255, 255));
        ViewCitizen.setText("View Citizen Details");
        ViewCitizen.setBorder(new javax.swing.border.SoftBevelBorder(0, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        ViewCitizen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewCitizenMouseClicked(evt);
            }
        });
        jPanel1.add(ViewCitizen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 310, 70));

        ViewVaccine.setBackground(new java.awt.Color(255, 51, 51));
        ViewVaccine.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        ViewVaccine.setForeground(new java.awt.Color(255, 255, 255));
        ViewVaccine.setText("View Vaccine Details");
        ViewVaccine.setBorder(new javax.swing.border.SoftBevelBorder(0, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        ViewVaccine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewVaccineMouseClicked(evt);
            }
        });
        ViewVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewVaccineActionPerformed(evt);
            }
        });
        jPanel1.add(ViewVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 310, 70));

        ViewVaccinated.setBackground(new java.awt.Color(255, 51, 51));
        ViewVaccinated.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        ViewVaccinated.setForeground(new java.awt.Color(255, 255, 255));
        ViewVaccinated.setText("View Vaccinated Details");
        ViewVaccinated.setBorder(new javax.swing.border.SoftBevelBorder(0, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        ViewVaccinated.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewVaccinatedMouseClicked(evt);
            }
        });
        jPanel1.add(ViewVaccinated, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 310, 70));

        ViewInfected.setBackground(new java.awt.Color(255, 51, 51));
        ViewInfected.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        ViewInfected.setForeground(new java.awt.Color(255, 255, 255));
        ViewInfected.setText("View Infected Details");
        ViewInfected.setBorder(new javax.swing.border.SoftBevelBorder(0, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        ViewInfected.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewInfectedMouseClicked(evt);
            }
        });
        jPanel1.add(ViewInfected, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 310, 70));

        topic.setFont(new java.awt.Font("Tekton Pro", 1, 48)); // NOI18N
        topic.setForeground(new java.awt.Color(255, 255, 255));
        topic.setText("PHI");
        jPanel1.add(topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 80, -1));

        logout.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        logout.setText("Log Out");
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 100, 30));

        background.setBackground(new java.awt.Color(255, 102, 51));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img/background.jpg"))); // NOI18N
        background.setText("jLabel1");
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewCitizenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewCitizenMouseClicked
        PHIViewCitizen citizen = new PHIViewCitizen();

        citizen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewCitizenMouseClicked

    private void ViewVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewVaccineActionPerformed
        
                      
    }//GEN-LAST:event_ViewVaccineActionPerformed


    private void ViewVaccineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewVaccineMouseClicked
       PHIViewVaccine vaccine = new PHIViewVaccine();

       vaccine.setVisible(true);
       this.dispose();

       
    }//GEN-LAST:event_ViewVaccineMouseClicked

    private void ViewVaccinatedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewVaccinatedMouseClicked
       PHIViewVaccinated vaccinated = new PHIViewVaccinated();

       vaccinated.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ViewVaccinatedMouseClicked

    private void ViewInfectedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewInfectedMouseClicked
       PHIViewInfected infected = new PHIViewInfected();

       infected.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ViewInfectedMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PHIHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PHIHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PHIHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PHIHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PHIHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewCitizen;
    private javax.swing.JButton ViewInfected;
    private javax.swing.JButton ViewVaccinated;
    private javax.swing.JButton ViewVaccine;
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel topic;
    // End of variables declaration//GEN-END:variables
}
